# Generated by Django 6.0.2 on 2026-03-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='platos/')),
                ('es_destacado', models.BooleanField(default=False, help_text='Aparecerá en el carrusel de inicio')),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='users.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('EVENTO', 'Catering y Logística para Eventos'), ('SUMINISTRO', 'Abastecimiento a Restaurantes Externos'), ('TRANSPORTE', 'Solo Transporte VIP/Artistas')], max_length=20)),
                ('nombre_entidad', models.CharField(help_text='Nombre del Festival o Restaurante cliente', max_length=200)),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha del servicio o suministro')),
                ('requiere_productos', models.BooleanField(default=False, verbose_name='¿Incluye alimentos/suministros?')),
                ('requiere_transporte', models.BooleanField(default=False, verbose_name='¿Requiere flota de transporte Koi?')),
                ('volumen_logistica', models.TextField(blank=True, help_text='Descripción del transporte (ej: 3 furgones refrigerados, 2 sedanes VIP)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('PROCESO', 'En Preparación/Tránsito'), ('COMPLETADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('productos_solicitados', models.ManyToManyField(blank=True, to='users.plato', verbose_name='Productos/Platos a suministrar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
