# Generated by Django 6.0.2 on 2026-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
