# Generated by Django 6.0.2 on 2026-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='respuesta',
            field=models.TextField(blank=True, help_text='Escribe la respuesta aquí. Al guardar se enviará este texto por correo al usuario.', null=True),
        ),
    ]
