"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SR-001 [INFORMATION DISCLOSURE] - SECRET_KEY nunca debe tener fallback hardcodeado
# Si la variable no está definida, Django debe fallar en arranque, no usar una clave débil
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY no está definida. "
        "Añade SECRET_KEY a tus variables de entorno o al fichero .env"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'amalvarosg.tech', 'www.amalvarosg.tech']
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'catalog',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',          # Compresión - debe ir antes de sessions
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=0) # Must be 0 for Neon Serverless
if db_from_env:
    DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django 4.2+ requiere usar STORAGES en lugar de DEFAULT_FILE_STORAGE / STATICFILES_STORAGE
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Configuración de redirecciones para autenticación
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# SR-003 [SESSION MANAGEMENT] - Configuración segura de sesiones (OWASP V3)
SESSION_COOKIE_AGE = 7200          # 2 horas de inactividad máxima
SESSION_COOKIE_HTTPONLY = True     # JS no puede leer la cookie de sesión
SESSION_COOKIE_SAMESITE = 'Lax'   # Protege contra CSRF cross-site
SESSION_SAVE_EVERY_REQUEST = False # No renueva sesión en cada petición (rendimiento)

# SR-004 [SECURITY HEADERS] Solo en producción
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# SR-002 [REPUDIATION / AUDIT LOGGING] - Logging de eventos de seguridad (OWASP V7)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '[{levelname}] {asctime} | {name} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
    },
    'loggers': {
        'django.security': {          # Intentos CSRF, SuspiciousOperation, etc.
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {           # Errores HTTP 4xx/5xx
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'koi.security': {             # Logger propio para eventos de la app
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# La carpeta física en tu ordenador/servidor
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# La URL que se verá en el navegador
MEDIA_URL = '/media/'

if os.environ.get('CLOUDINARY_URL'):
    # Al usar cloudinary-storage, no hace falta forzar MEDIA_URL de forma manual.
    # El backend de almacenamiento ya se encarga de generar la URL completa.
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 25  # segundos - evita el 502 de Render por timeout de Gunicorn (30s)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ===== CONFIGURACIÓN JAZZMIN PARA DASHBOARD =====
JAZZMIN_SETTINGS = {
    "site_title": "Gestión Koi Enterprise",
    "site_header": "Koi Enterprise",
    "site_brand": "Koi Enterprise",
    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",
    "welcome_sign": "Bienvenido al Panel de Control de Koi Enterprise",
    "copyright": "Koi Enterprise",
    "topmenu_links": [
        {"name": "Sitio Web", "url": "home"},
    ],
    "icons": {
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "users.User": "fas fa-user-secret",
        "users.Organization": "fas fa-building",
        "users.MensajeContacto": "fas fa-envelope",
        "catalog.Producto": "fas fa-box-open",
        "catalog.Plato": "fas fa-utensils",
        "catalog.Categoria": "fas fa-tags",
        "catalog.CategoriaDeProducto": "fas fa-tag",
        "catalog.Ingrediente": "fas fa-leaf",
        "orders.SolicitudServicio": "fas fa-concierge-bell",
        "orders.PedidoMercado": "fas fa-shopping-cart",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-warning",
    "accent": "accent-warning",
    "brand_colour": "navbar-dark",
}