# Generated by Django 6.0.2 on 2026-04-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMercadoNegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='banners_mercado/')),
                ('enlace', models.URLField(blank=True, help_text='URL opcional al hacer clic en el banner')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, help_text='Si se deja vacío, aparece al inicio de la página (sobre todas las categorías).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Banner Mercado Negro',
                'verbose_name_plural': 'Banners Mercado Negro',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='BannerNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('enlace', models.URLField(blank=True, help_text='URL opcional al hacer clic en el banner')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, help_text="Si se deja vacío, aparece en 'Ver Todo' y en Home.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'Banner Normal',
                'verbose_name_plural': 'Banners Normales',
                'ordering': ['orden'],
            },
        ),
    ]
