# Generated by Django 6.0.2 on 2026-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bannermercadonegro_bannernormal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannernormal',
            name='solo_en_home',
            field=models.BooleanField(default=False, help_text='Si se marca, el banner solo aparecerá en la página principal y no en el menú general.', verbose_name='Solo en Home'),
        ),
    ]
