# Generated by Django 6.0.2 on 2026-04-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bannernormal_solo_en_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('FIJO', 'Importe Fijo (€)')], default='PORCENTAJE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Ej: 10 para 10% o 10€', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.PositiveIntegerField(default=1, help_text='Cuántas veces se puede usar en total')),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto (Mercado)', 'verbose_name_plural': 'Productos (Mercado)'},
        ),
        migrations.CreateModel(
            name='OfertaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total Pack')),
                ('activo', models.BooleanField(default=True)),
                ('auto_aplicar', models.BooleanField(default=False, help_text='Si el usuario añade estos productos manualmente al carrito, se aplicará el descuento automáticamente.', verbose_name='Auto-aplicar')),
                ('productos', models.ManyToManyField(related_name='ofertas', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Oferta Mercado Negro',
                'verbose_name_plural': 'Ofertas Mercado Negro',
            },
        ),
        migrations.AddField(
            model_name='bannermercadonegro',
            name='oferta',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona una oferta, al clicar el banner se añadirán los productos al carrito con precio especial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.ofertamercado'),
        ),
        migrations.CreateModel(
            name='OfertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total Pack')),
                ('activo', models.BooleanField(default=True)),
                ('platos', models.ManyToManyField(related_name='ofertas', to='catalog.plato')),
            ],
            options={
                'verbose_name': 'Oferta de Servicio/Platos',
                'verbose_name_plural': 'Ofertas de Servicio/Platos',
            },
        ),
        migrations.AddField(
            model_name='bannernormal',
            name='oferta',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona una oferta, al clicar el banner se pre-seleccionarán los platos de la oferta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.ofertaservicio'),
        ),
    ]
