# Generated by Django 6.0.2 on 2026-04-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cupon_alter_producto_options_ofertamercado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertamercado',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='ofertaservicio',
            name='platos',
        ),
        migrations.AlterField(
            model_name='ofertamercado',
            name='auto_aplicar',
            field=models.BooleanField(default=False, help_text='Si el usuario añade estos productos manualmente al carrito (en las cantidades indicadas), se aplicará el descuento automáticamente.', verbose_name='Auto-aplicar'),
        ),
        migrations.CreateModel(
            name='ItemOfertaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.ofertamercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOfertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.ofertaservicio')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.plato')),
            ],
        ),
    ]
