# Generated by Django 6.0.2 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_ofertamercado_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertamercado',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Total Pack'),
        ),
        migrations.AlterField(
            model_name='ofertaservicio',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Total Pack'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de Venta (Mercado Negro)'),
        ),
    ]
