# Generated by Django 6.0.2 on 2026-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_ofertamercado_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='usos_maximos_por_usuario',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas veces puede usarlo cada usuario individualmente'),
        ),
    ]
