# Generated by Django 6.0.2 on 2026-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('EVENTO', 'Catering para Evento'), ('SUMINISTRO', 'Suministro a Restaurante'), ('TRANSPORTE', 'Logística y Transporte VIP')], default='EVENTO', max_length=20)),
                ('nombre_entidad', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiere_productos', models.BooleanField(default=False)),
                ('detalles_cantidades', models.JSONField(blank=True, default=dict)),
                ('requiere_transporte', models.BooleanField(default=False)),
                ('detalles_transporte', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACEPTADO', 'Presupuestado / Aceptado'), ('EN_CAMINO', 'En Reparto'), ('COMPLETADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('productos_solicitados', models.ManyToManyField(blank=True, to='catalog.plato')),
            ],
        ),
    ]
