# Generated by Django 6.0.2 on 2026-03-17 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('EVENTO', 'Catering para Evento'), ('SUMINISTRO', 'Suministro a Restaurante'), ('TRANSPORTE', 'Logística y Transporte VIP')], default='EVENTO', max_length=20)),
                ('nombre_entidad', models.CharField(help_text='Nombre de la empresa o del evento', max_length=200)),
                ('fecha_entrega', models.DateField()),
                ('requiere_productos', models.BooleanField(default=True)),
                ('requiere_transporte', models.BooleanField(default=False)),
                ('volumen_logistica', models.TextField(blank=True, help_text='Detalles sobre peso, refrigeración necesaria, etc.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACEPTADO', 'Presupuestado / Aceptado'), ('EN_CAMINO', 'En Reparto'), ('COMPLETADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('productos_solicitados', models.ManyToManyField(blank=True, to='catalog.plato', verbose_name='Platos/Productos de la carta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicios',
            },
        ),
    ]
