# Generated by Django 6.0.2 on 2026-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(default='EVENTO', max_length=150),
        ),
    ]
