# Generated by Django 6.0.2 on 2026-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0002_solicitudservicio_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudservicio',
            options={},
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='detalles_cantidades',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='detalles_transporte',
            field=models.JSONField(blank=True, default=dict, help_text="Guarda los vehículos seleccionados y sus cantidades: {'Limusina': 2, 'Jet': 1}", null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='nombre_entidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='productos_solicitados',
            field=models.ManyToManyField(blank=True, to='catalog.plato'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='requiere_productos',
            field=models.BooleanField(default=False),
        ),
    ]
