# Generated by Django 6.0.2 on 2026-04-12 12:22

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_solicitudservicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EVENTO', 'Catering para Evento'), ('SUMINISTRO', 'Suministro a Restaurante'), ('TRANSPORTE', 'Logística y Transporte VIP')], max_length=150, verbose_name='Tipos de Servicio'),
        ),
    ]
