# Generated by Django 6.0.2 on 2026-03-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_solicitudservicio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='volumen_logistica',
        ),
    ]
