# Generated by Django 6.0.2 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_solicitudservicio_volumen_logistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='detalles_transporte',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(default='EVENTO', max_length=255),
        ),
    ]
