# Generated by Django 6.0.2 on 2026-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_mensajepedidomercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomercado',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
