# Generated by Django 6.0.2 on 2026-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pedidomercado_stock_descontado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajepedidomercado',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajesolicitud',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
