# Generated by Django 6.0.2 on 2026-04-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cupon_alter_producto_options_ofertamercado_and_more'),
        ('orders', '0009_mensajepedidomercado_leido_mensajesolicitud_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomercado',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='catalog.cupon'),
        ),
        migrations.AddField(
            model_name='pedidomercado',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidomercado',
            name='oferta_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='catalog.ofertamercado'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='oferta_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalog.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='precio_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si viene de una oferta, este será el precio final acordado.', max_digits=12, null=True),
        ),
    ]
