# Generated by Django 6.0.2 on 2026-04-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_ofertamercado_precio_total_and_more'),
        ('orders', '0010_pedidomercado_cupon_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalog.cupon'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
